---
- hosts: localhost
  tasks:
  - name: Read Terraform State File
    ansible.builtin.slurp:
      src: ~/jenkins-infra/terraform.tfstate
    register: statefile

  - name: Set statefile contents to variable
    ansible.builtin.set_fact:
      statefile_json: "{{ statefile.content | b64decode }}"

  - name: Set Jenkins Server Public IP to variable
    ansible.builtin.set_fact:
      jenkins_server_ip: "{{ statefile_json | json_query(public_ip_query) }}"
    vars:
      public_ip_query: "resources[0].instances[?name==jenkins_server].attributes.public_ip"

- hosts: jenkins_server
  become: true
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: "{{ jenkins_ssh_key }}"
  tasks:
  - name: Install yum-utils
    dnf:
      name: yum-utils
      state: installed

  - name: Overlay ext4 filesystem on Jenkins data device
    community.general.filesystem:
      dev: /dev/xvdb
      fstype: ext4

  - name: Mount EBS Volume for Jenkins data
    ansible.posix.mount:
      path: /mnt/jenkins
      src: /dev/xvdb
      fstype: ext4
      state: mounted

  - name: Add docker-ce repository
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker Engine
    ansible.builtin.dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: installed

  - name: Add {{ ansible_user }} to docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true

  - name: Give directory ownership to Docker group
    ansible.builtin.file:
      path: /mnt/jenkins/
      owner: "{{ ansible_user }}"
      group: docker
      recurse: true

  - name: Start Docker Service
    systemd:
      name: docker
      state: started

  - name: Install python3
    dnf:
      name: python3
      state: installed

  - name: Install Docker SDK python module
    ansible.builtin.pip:
      name: docker
      state: present

  - name: Create bridge network in Docker named 'jenkins'
    community.docker.docker_network:
      name: jenkins

  - name: Start Jenkins Docker Container
    community.docker.docker_container:
      name: jenkins_master
      image: jenkins/jenkins:lts-jdk11
      state: started
      detach: true
      ports:
        - "80:8080"
        - "50000:50000"
      volumes:
        - "/mnt/jenkins:/var/jenkins_home"

- hosts: jenkins_agent
  become: true
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: "{{ jenkins_ssh_key }}"
  tasks:
  - name: Install openJDK & git
    package:
      name:
        - java-11-openjdk-devel
        - git
      state: installed

  - name: Create jenkins user
    ansible.builtin.user:
      name: jenkins
      create_home: true
      home: /var/jenkins_home/

  - name: Create .ssh directory for jenkins user
    ansible.builtin.file:
      path: /var/jenkins_home/.ssh
      state: directory

  - name: Generate OpenSSH keypair
    community.crypto.openssh_keypair:
      path: /var/jenkins_home/.ssh/ssh_id_rsa
      owner: jenkins
      group: jenkins
    register: jenkins_keypair

  - name: debug
    ansible.builtin.debug:
      var: jenkins_keypair

  - name: Add public key to authorized_keys for jenkins user
    ansible.builtin.lineinfile:
      path: /var/jenkins_home/.ssh/authorized_keys  #"{{ jenkins_keypair.filename }}/authorized_keys"
      line: "{{ jenkins_keypair.public_key }}"
      create: true
      owner: jenkins
      group: jenkins

  - name: Add docker-ce repository
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker Engine
    ansible.builtin.dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: installed

  - name: Add {{ ansible_user }} to docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true

  - name: Give directory ownership to Docker group
    ansible.builtin.file:
      path: /mnt/jenkins/
      owner: "{{ ansible_user }}"
      group: docker
      recurse: true

  - name: Start Docker Service
    systemd:
      name: docker
      state: started
